apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-service-opa.fullname" . }}
  labels:
    {{- include "self-service-opa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8181
      protocol: TCP
      name: http
  selector:
    {{- include "self-service-opa.selectorLabels" . | nindent 4 }}
