# Default values for self-service-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

self_service_api:
  environment: "staging"
  # -- Where to reach the OPA
  opa_url: "http://self-service-opa"

  # TODO: consolidate
  # -- Where to reach the UCS machine
  ucs_base_url: "http://univention-corporate-server"
  ucs_selfservice_prefix: "http://univention-corporate-server/univention/internal/umc/"

  # -- Define Basic auth password with the UMC.
  # Example: `"univention"`
  auth_secret: null

  # -- The URL prefix which this service has to grab
  url_prefix: "/univention/command/passwordreset/"

image:
  registry: "registry.souvap-univention.de"
  repository: "souvap/tooling/images/self-service-api/self-service-api"
  pullPolicy: "Always"
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  # -- Set this to `true` in order to enable the installation on Ingress related objects.
  enabled: false
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- The hostname. This parameter has to be supplied. Example `portal.example`.
  host: null
  paths:
    - pathType: "Prefix"
      path: "/univention/command/passwordreset/(.*)"
  tls:
    enabled: true
    secretName: ""


## Istio support
istio:
  # -- Set this to `true` in order to enable the installation on Istio related objects.
  enabled: true
  # -- The hostname. This parameter has to be supplied. Example `portal.example`.
  host: null
  virtualService:
    enabled: true
    annotations:
  gateway:
    enabled: false
    annotations:
    selectorIstio: "ingressgateway"
    externalGatewayName: "swp-istio-gateway"
    tls:
      enabled: true
      httpsRedirect: true
      secretName: ""


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
